# TODO:
# add `$java\` and configure it
# configure `$status\` which is disabled by default
format = """
[$directory\
$git_branch\
$git_commit\
$git_status\
$package\
$rust\
$cmd_duration\
$line_break\
$jobs\
$shell\
$status](white) """

# add_newline = false

[jobs]
style = "bg:green fg:#1d2021"
format = "[$symbol $number ]($style)"

[status]
disabled = false
symbol="✖ "
style = "bg:red fg:#fbf1c7"
format = "[](bg:red fg:black)[$symbol$status ]($style)[](fg:red)"

[shell]
disabled = false
style = "bg:green fg:#1d2021"
format = "[$indicator ]($style)[](green)"

[directory]
fish_style_pwd_dir_length = 2
read_only = " "
style = "bg:#1d2021"
read_only_style = "bg:#1d2021 red"
format = "[$path]($style)[$read_only ]($read_only_style)[](#1d2021)"

[git_branch]
symbol = " "
style = "bg:yellow fg:#1d2021"
format = "[ ](bg:yellow fg:black)[$symbol$branch ]($style)[](yellow)"

[git_commit]
style = "fg:#1d2021 bg:red"
format="[ ](bg:red fg:black)[\\($hash$tag\\) ]($style)[](fg:red)"

[git_status]
style = "fg:red bg:#1d2021 bold"
ahead="⇡ "
behind="⇣ "
diverged="⇕ "
format = "([ ](bg:#1d2021 fg:black)[\\[$all_status$ahead_behind\\] ]($style)[](#1d2021))"

[package]
style = "bg:blue #fbf1c7"
format = "[ ](bg:blue fg:black)[$version ]($style)[](fg:blue)"

[rust]
style = "bg:cyan #fbf1c7"
format = "[ ](bg:cyan fg:black)[rust ]($style)[$version ]($style)[](fg:cyan)"

[python]
symbol = " "

[character]
success_symbol = "[ \\$ ](fg:black bg:green)[](bold green)"
error_symbol= "[ \\$ ](fg:black bg:red)[](bold red)"
