# TODO:
# add `$java\` and configure it
# configure `$status\` which is disabled by default
format = """
[$directory\
$git_branch\
$git_commit\
$git_status\
$package\
$cmd_duration\
$line_break\
$jobs\
$shell\
$status](white) """

# add_newline = false

[cmd_duration]
format = " took [$duration]($style) "

[jobs]
style = "bg:green fg:#1e2127"
format = "[$symbol $number]($style)"

[status]
disabled = false
symbol=" ✖ "
style = "bg:red fg:#1e2127"
format = "[](bg:red fg:#1e2127)[$symbol$status ]($style)[](fg:red)"

[shell]
disabled = false
fish_indicator = " λ"
format = "[$indicator ](bg:green fg:#1e2127)[](green)"

[directory]
fish_style_pwd_dir_length = 2
read_only = " "
style = "bg:#282c34"
read_only_style = "bg:#282c34 red"
format = "[$path]($style)[$read_only ]($read_only_style)[](#282c34)"

[git_branch]
symbol = " "
style = "bg:yellow fg:#1e2127"
format = "[ ](bg:yellow fg:#1e2127)[$symbol$branch ]($style)[](yellow)"

[git_commit]
style = "fg:#1e2127 bg:red"
format="[ ](bg:red fg:#1e2127)[\\($hash$tag\\) ]($style)[](fg:red)"

[git_status]
style = "fg:red bg:#282c34 bold"
ahead="⇡ "
behind="⇣ "
diverged="⇕ "
format = "([ ](bg:#282c34 fg:#1e2127)[\\[$all_status$ahead_behind\\] ]($style)[](#282c34))"

[package]
style = "bg:blue #1e2127"
format = "[ ](bg:blue fg:#1e2127)[$version ]($style)[](fg:blue)"

[rust]
style = "bg:cyan #1e2127"
format = "[ ](bg:cyan fg:#1e2127)[rust ]($style)[$version ]($style)[](fg:cyan)"

[python]
symbol = " "

[character]
success_symbol = "[ \\$ ](fg:black bg:green)[](bold green)"
error_symbol= "[ \\$ ](fg:black bg:red)[](bold red)"
